# Generated by Django 4.2.2 on 2023-06-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_about_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='isHidden',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
