# Generated by Django 4.2.2 on 2023-06-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_skill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='blogs/')),
                ('content', models.TextField()),
                ('skills', models.ManyToManyField(related_name='blogs', to='portfolio.skill')),
            ],
        ),
    ]
