# Generated by Django 4.2.2 on 2023-06-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_education_emailmessage_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-createdAt']},
        ),
    ]
