# Generated by Django 4.2.2 on 2023-06-21 16:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='About',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
