# Generated by Django 4.2.2 on 2023-06-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_blog_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='preview',
        ),
    ]
