# Generated by Django 4.2.2 on 2023-06-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_blog_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='email',
            new_name='businessEmail',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='email1',
            new_name='contactEmail',
        ),
    ]
