# Generated by Django 4.2.2 on 2023-06-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_email_about_businessemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='About',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(),
        ),
    ]
